version: '3.8'
services:
  game-db:
    image: postgres
    environment:
      POSTGRES_USER: game_user
      POSTGRES_PASSWORD: game_pass
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    volumes:
      - game_data:/var/lib/postgresql/data
  
  game-service:
    build:
      context: ./game-service
    depends_on:
      - game-db
    environment:
      - DATABASE_URL=postgresql://game_user:game_pass@game-db:5432/game_db
    ports:
      - "8000:8000"

  user-game-db:
    image: postgres
    environment:
      POSTGRES_DB: user_game_db
      POSTGRES_USER: user_game_user
      POSTGRES_PASSWORD: user_game_pass
    volumes:
      - user_game_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  user-game-service:
    build:
      context: ./user-game-service
    depends_on:
      - user-game-db
    environment:
      - DATABASE_URL=postgresql://user_game_user:user_game_pass@user-game-db:5432/user_game_db
    ports:
      - "8001:8001"
  
  gateway-graphql-service:
    build: ./gateway-graphql-service
    ports:
      - "3000:3000"
    depends_on:
      - game-service
      - user-game-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/graphql"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  game_data:
  user_game_data:
    